// <auto-generated />
using DinosaurAPI.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DinosaurAPI.Migrations
{
    [DbContext(typeof(DinoDBContext))]
    [Migration("20210817101607_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DinosaurAPI.Models.DinoModel", b =>
                {
                    b.Property<int>("DinoModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Defence")
                        .HasColumnType("REAL");

                    b.Property<int>("DinoLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DinoSoundLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("DinosaurName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Food")
                        .HasColumnType("REAL");

                    b.Property<double>("Health")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageLink")
                        .HasColumnType("TEXT");

                    b.Property<double>("Intelligence")
                        .HasColumnType("REAL");

                    b.Property<double>("Stamina")
                        .HasColumnType("REAL");

                    b.Property<double>("Strenght")
                        .HasColumnType("REAL");

                    b.Property<string>("TypeOfDino")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueString")
                        .HasColumnType("TEXT");

                    b.HasKey("DinoModelID");

                    b.ToTable("Dinosaurs");
                });
#pragma warning restore 612, 618
        }
    }
}
