using DinosaurAPI.HelperClasses;
using DinosaurAPI.Interfaces;
using DinosaurAPI.JSONInputClasses;
using DinosaurAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DinosaurAPI.ImplementationClasses
{
    public class GenerateLandDinov1 : IDinoGenerator
    {
        public DinoModel generateDino(DinoJSONInput dinoJSONInput)
        {

        //Fill up the dinomodel
        //public int DinoLevel { get; set; } - DONE
        //public string DinosaurName { get; set; } - DONE
        //public string TypeOfDino { get; set; } - DONE
        //public double Health { get; set; } - DONE
        //public double Stamina { get; set; } - DONE
        //public double Strenght { get; set; } - DONE
        //public double Defence { get; set; } - DONE
        //public double Food { get; set; } - DONE
        //public double Intelligence { get; set; } - DONE
        //public string ImageLink { get; set; } - DONE
        //public string DinoSoundLink { get; set; } - DONE

            //Initiate the dinosaurmodel
            var tempGeneratedDinosaur = new DinoModel();

            //Set the id of the dinosaur coming from id creation interface and implementation
            ICreateUniqueID createUniqueID = new CreateUniqueIDv1();
            tempGeneratedDinosaur.UniqueString = createUniqueID.CreateUniqueID();

            //Level of the dino is always starting on level one
            tempGeneratedDinosaur.DinoLevel = 1;

            // Name is coming from input
            tempGeneratedDinosaur.DinosaurName = dinoJSONInput.DinosaurName;

            //Type of Dinosaur is LandDino for this implementation
            //TODO: Use enums for this
            tempGeneratedDinosaur.TypeOfDino = "LandDino";

            //DinoHealth is generated by health implementation for LandDinos
            IStatsGenerator healthGenerator = new GenerateHealthLandDinov1();
            tempGeneratedDinosaur.Health = healthGenerator.GenerateStats();

            //DinoStamina is generated by stamina implementation for LandDinos
            IStatsGenerator staminaGenerator = new GenerateStaminaLandDinov1();
            tempGeneratedDinosaur.Stamina = staminaGenerator.GenerateStats();

            //DinoStrenght is generated by strenght implementation for LandDinos
            IStatsGenerator strenghtGenerator = new GenerateStrenghtLandDinov1();
            tempGeneratedDinosaur.Strenght = strenghtGenerator.GenerateStats();

            //DinoDefence is generated by defence implementation for LandDinos
            IStatsGenerator defenceGenerator = new GenerateDefenceLandDinov1();
            tempGeneratedDinosaur.Defence = defenceGenerator.GenerateStats();

            //DinoFood is generated by food implementation for LandDinos
            IStatsGenerator foodGenerator = new GenerateFoodLandDinov1();
            tempGeneratedDinosaur.Food = foodGenerator.GenerateStats();

            //DinoIntelligence is generated by intelligence implementation for LandDinos
            IStatsGenerator intelligenceGenerator = new GenerateIntelligenceLandDinov1();
            tempGeneratedDinosaur.Intelligence = intelligenceGenerator.GenerateStats();

            //Dino Image or Character is picked randomly by imagehelper class
            DinosaurImageHelper dinosaurCharacter = new DinosaurImageHelper();
            tempGeneratedDinosaur.ImageLink = dinosaurCharacter.GenerateLandDinoImage();

            //DinosaurSoundEffect will be picked by implementation later on for now they all have one and the same sound setted here.
            tempGeneratedDinosaur.DinoSoundLink = "https://drive.google.com/file/d/1qBtssqXyGywgnOuzOk1mdYyeBBlysDPK/view?usp=sharing";


            return tempGeneratedDinosaur;
        }
    }
}
